name: Build and Run Haiku Generator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0"

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build HaikuGenerator
        run: |
          dotnet build src/HaikuGenerator/HaikuGenerator.csproj --configuration Release
